# -*- coding: utf-8 -*-
"""atividade 01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CR3pEurRtNFerUY_cc1TptBmwQNTHGi0
"""

matriz = []
print("Digite os valores para a matriz 3x3:")

for i in range(3):
    linha = []
    for j in range(3):
        valor = int(input(f"Elemento [{i}][{j}]: "))
        linha.append(valor)
    matriz.append(linha)


k = int(input("\n Digite o valor do multiplicador k: "))


print("\n Matriz Original")
for linha in matriz:
    print(linha)


for i in range(3):
    matriz[i][i] = matriz[i][i] * k


print(f"\n Matriz com a Diagonal multiplicada por {k}")
for linha in matriz:
    print(linha)